name: latlong_to_place
description: A Flutter library to fetch device LatLng via geolocator and convert it into rich PlaceInfo via the null-safe geocoding plugin.
version: 0.0.2
homepage: https://github.com/Arpit980jai/latlng_to_place
repository: https://github.com/Arpit980jai/latlng_to_place
publisher: arpitjai.com

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2    # for device location
  geocoding: ^2.0.5     # for reverse-geocoding

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/topbanner.png
    - assets/bottombanner.png